#!/bin/bash
################################################################################
# AppRun - Launcher script for MemScreen AppImage
#
# This script is executed when the AppImage is run. It sets up the environment
# and launches the MemScreen application.
################################################################################

# Get the directory where this script is located
SELF=$(readlink -f "$0")
HERE=${SELF%/*}

# Set up environment variables for the bundled application
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export PYTHONPATH="${HERE}/usr/lib/python3.8/site-packages:${PYTHONPATH}"

# Set XDG data directories to use bundled paths
export XDG_DATA_HOME="${HERE}/usr/share"
export XDG_CONFIG_HOME="${HOME}/.config/MemScreen"

# Create user data directory if it doesn't exist
mkdir -p "${XDG_CONFIG_HOME}"
mkdir -p "${HOME}/.local/share/MemScreen"

# Launch MemScreen
exec "${HERE}/usr/bin/MemScreen" "$@"
